version: '3'

networks:
  smart_room:

services:

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db_backup:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=STiN7pR0y3Ct
      - MYSQL_DATABASE=openhab2
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
    networks:
      - smart_room

  openhab:
    build: 
      context: openhab
      dockerfile: Dockerfile
    container_name: openhab
    ports: 
      - "9000:8080"
    networks:
      - smart_room

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    volumes:
      - ./back:/app
    ports:
      - "9002:5000"
    networks:
      - smart_room

  front:
    build:
      context: front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "9004:3000"
    networks:
      - smart_room
